# Generated by Django 5.0.6 on 2024-07-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(help_text='Image size : 256px X 256px', upload_to='services')),
                ('status', models.CharField(help_text='Please enter active or inactive.', max_length=10)),
            ],
        ),
    ]
