# Generated by Django 5.0.6 on 2024-07-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_feedback_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_us',
            name='about_site',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about_us',
            name='contact_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='about_us',
            name='contact_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='about_us',
            name='facebook_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='about_us',
            name='instagram_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='about_us',
            name='logo',
            field=models.ImageField(null=True, upload_to='about'),
        ),
        migrations.AddField(
            model_name='about_us',
            name='map_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about_us',
            name='office_address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about_us',
            name='support_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='about_us',
            name='support_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='about_us',
            name='x_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
