# Generated by Django 5.0.6 on 2024-07-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=150)),
                ('job_description', models.TextField()),
                ('posted_on', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('experience', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('1', 'Active'), ('0', 'Inactive')], default='1', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
